# Generated by Django 5.2.7 on 2025-10-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
    ]
